// This file provides a safe way to import icons from react-icons
// It handles the CommonJS/ESM compatibility issues that can occur on the server

// Import all FA icons in a single import statement
import {
  FaTimes,
  FaBars,
  FaFacebook,
  FaInstagram,
  FaTwitter,
  FaPinterest,
  FaCalendarAlt,
  FaUser,
  FaEnvelope,
  FaPhone,
  FaGlobe,
  FaUsers,
  FaTrash,
  FaPlus,
  FaBan,
  FaSignOutAlt,
  FaSearch,
  FaEdit,
  FaCheck,
  FaMapMarkerAlt,
  FaBed,
  FaBath,
  FaRulerCombined,
  FaDirections,
  FaMapPin,
  FaLock,
  FaTicketAlt,
  FaCopy,
  FaExclamationTriangle,
  FaArrowRight,
  FaChevronLeft,
  FaChevronRight,
  FaArrowLeft
} from 'react-icons/fa';

// Import all SL icons in a single import statement
import { SlArrowRight, SlArrowLeft } from 'react-icons/sl';

// Re-export all icons
export {
  FaTimes,
  FaBars,
  FaFacebook,
  FaInstagram,
  FaTwitter,
  FaPinterest,
  FaCalendarAlt,
  FaUser,
  FaEnvelope,
  FaPhone,
  FaGlobe,
  FaUsers,
  FaTrash,
  FaPlus,
  FaBan,
  FaSignOutAlt,
  FaSearch,
  FaEdit,
  FaCheck,
  FaMapMarkerAlt,
  FaBed,
  FaBath,
  FaRulerCombined,
  FaDirections,
  FaMapPin,
  FaLock,
  FaTicketAlt,
  FaCopy,
  FaExclamationTriangle,
  FaArrowRight,
  FaChevronLeft,
  FaChevronRight,
  FaArrowLeft,
  SlArrowRight,
  SlArrowLeft
};
